import {
  ServiceOffer,
  BookingAppointment,
  DayScheduleConfig,
  PartnerProfessional,
  PartnerAppointmentItem,
} from './types';

export const DEFAULT_WEEK_SCHEDULE: DayScheduleConfig[] = [
  {
    dayOfWeek: 0,
    dayName: 'Domingo',
    active: false,
    openTime: '09:00',
    closeTime: '14:00',
    breaks: [],
  },
  {
    dayOfWeek: 1,
    dayName: 'Segunda-feira',
    active: true,
    openTime: '09:00',
    closeTime: '19:00',
    breaks: [{ id: 'brk-1', label: 'Almoço', start: '12:30', end: '13:30' }],
  },
  {
    dayOfWeek: 2,
    dayName: 'Terça-feira',
    active: true,
    openTime: '09:00',
    closeTime: '19:00',
    breaks: [{ id: 'brk-2', label: 'Almoço', start: '12:30', end: '13:30' }],
  },
  {
    dayOfWeek: 3,
    dayName: 'Quarta-feira',
    active: true,
    openTime: '09:00',
    closeTime: '19:00',
    breaks: [{ id: 'brk-3', label: 'Almoço', start: '12:30', end: '13:30' }],
  },
  {
    dayOfWeek: 4,
    dayName: 'Quinta-feira',
    active: true,
    openTime: '09:00',
    closeTime: '20:00',
    breaks: [
      { id: 'brk-4', label: 'Almoço', start: '12:30', end: '13:30' },
      { id: 'brk-4b', label: 'Pausa Café', start: '16:30', end: '17:00' },
    ],
  },
  {
    dayOfWeek: 5,
    dayName: 'Sexta-feira',
    active: true,
    openTime: '08:30',
    closeTime: '20:30',
    breaks: [{ id: 'brk-5', label: 'Almoço', start: '12:30', end: '13:30' }],
  },
  {
    dayOfWeek: 6,
    dayName: 'Sábado',
    active: true,
    openTime: '08:00',
    closeTime: '19:00',
    breaks: [{ id: 'brk-6', label: 'Almoço Rápido', start: '13:00', end: '13:45' }],
  },
];

export const INITIAL_PROFESSIONALS: PartnerProfessional[] = [
  {
    id: 'prof-1',
    name: 'Lucas Silva',
    role: 'Barbeiro Master',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    phone: '(11) 98123-4567',
    specialties: ['Corte Degradê', 'Barboterapia', 'Pigmentação'],
    color: '#059669', // Emerald
    slotDurationMinutes: 45,
    useCustomSchedule: false,
    schedule: JSON.parse(JSON.stringify(DEFAULT_WEEK_SCHEDULE)),
  },
  {
    id: 'prof-2',
    name: 'João Santos',
    role: 'Cabeleireiro & Visagista',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    phone: '(11) 97234-5678',
    specialties: ['Corte Tesoura', 'Coloração', 'Escova Modelada'],
    color: '#2563eb', // Blue
    slotDurationMinutes: 50,
    useCustomSchedule: false,
    schedule: JSON.parse(JSON.stringify(DEFAULT_WEEK_SCHEDULE)),
  },
  {
    id: 'prof-3',
    name: 'Camila Rocha',
    role: 'Manicure & Nail Designer',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    phone: '(11) 96345-6789',
    specialties: ['Esmaltação em Gel', 'Alongamento Fibra', 'Spa dos Pés'],
    color: '#db2777', // Pink
    slotDurationMinutes: 60,
    useCustomSchedule: true,
    schedule: JSON.parse(JSON.stringify(DEFAULT_WEEK_SCHEDULE)),
  },
  {
    id: 'prof-4',
    name: 'Juliana Mendes',
    role: 'Designer de Sobrancelhas',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    phone: '(11) 95456-7890',
    specialties: ['Henna', 'Lash Lifting', 'Micropigmentação'],
    color: '#7c3aed', // Purple
    slotDurationMinutes: 30,
    useCustomSchedule: false,
    schedule: JSON.parse(JSON.stringify(DEFAULT_WEEK_SCHEDULE)),
  },
];

// Helper to get formatted ISO date string YYYY-MM-DD
const getTodayIso = (offsetDays = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_PARTNER_APPOINTMENTS: PartnerAppointmentItem[] = [
  {
    id: 'appt-1',
    protocolCode: '#VGA-12345',
    professionalId: 'prof-1',
    professionalName: 'Lucas Silva',
    clientName: 'Anderson Silva',
    clientPhone: '+5511987654321',
    serviceTitle: 'Corte Degradê Navalhado',
    serviceCategory: 'cabelo',
    price: 45.0,
    dateStr: getTodayIso(0),
    startTime: '14:30',
    endTime: '15:15',
    status: 'EM_ATENDIMENTO',
    notes: 'Cliente prefere degradê alto e acabamento navalhado.',
  },
  {
    id: 'appt-2',
    protocolCode: '#VGA-20491',
    professionalId: 'prof-2',
    professionalName: 'João Santos',
    clientName: 'Rodrigo Alcantara',
    clientPhone: '+5511977771122',
    serviceTitle: 'Corte Clássico na Tesoura',
    serviceCategory: 'cabelo',
    price: 55.0,
    dateStr: getTodayIso(0),
    startTime: '15:30',
    endTime: '16:15',
    status: 'CONFIRMADO',
    notes: 'Primeira vez no salão.',
  },
  {
    id: 'appt-3',
    protocolCode: '#VGA-FLASH-1',
    professionalId: 'prof-1',
    professionalName: 'Lucas Silva',
    clientName: 'Vaga Aberta no Vagou',
    clientPhone: '',
    serviceTitle: 'Corte Masculino + Barba',
    serviceCategory: 'barba',
    price: 40.0,
    dateStr: getTodayIso(0),
    startTime: '16:30',
    endTime: '17:15',
    status: 'VAGA_PUBLICADA',
    notes: 'Oferta relâmpago ativa no app com desconto!',
  },
  {
    id: 'appt-4',
    protocolCode: '#VGA-FREE-1',
    professionalId: 'prof-3',
    professionalName: 'Camila Rocha',
    clientName: 'Horário Livre',
    clientPhone: '',
    serviceTitle: 'Manicure & Pedicure',
    serviceCategory: 'unhas',
    price: 50.0,
    dateStr: getTodayIso(0),
    startTime: '17:30',
    endTime: '18:30',
    status: 'HORARIO_LIVRE',
    notes: 'Cadeira vazia. Clique em Publicar para anunciar.',
  },
  {
    id: 'appt-5',
    protocolCode: '#VGA-44123',
    professionalId: 'prof-4',
    professionalName: 'Juliana Mendes',
    clientName: 'Beatriz Costa',
    clientPhone: '+5511988884433',
    serviceTitle: 'Design de Sobrancelhas + Henna',
    serviceCategory: 'beleza',
    price: 35.0,
    dateStr: getTodayIso(0),
    startTime: '18:00',
    endTime: '18:30',
    status: 'CONFIRMADO',
  },
  {
    id: 'appt-6',
    protocolCode: '#VGA-10293',
    professionalId: 'prof-1',
    professionalName: 'Lucas Silva',
    clientName: 'Felipe Marques',
    clientPhone: '+5511999998877',
    serviceTitle: 'Barboterapia Completa',
    serviceCategory: 'barba',
    price: 35.0,
    dateStr: getTodayIso(1), // Amanhã
    startTime: '10:00',
    endTime: '10:45',
    status: 'CONFIRMADO',
  },
  {
    id: 'appt-7',
    protocolCode: '#VGA-10294',
    professionalId: 'prof-2',
    professionalName: 'João Santos',
    clientName: 'Gabriel Souza',
    clientPhone: '+5511988887766',
    serviceTitle: 'Corte + Lavagem Especial',
    serviceCategory: 'cabelo',
    price: 50.0,
    dateStr: getTodayIso(1), // Amanhã
    startTime: '11:00',
    endTime: '11:50',
    status: 'CONFIRMADO',
  },
];

export const MOCK_OFFERS: ServiceOffer[] = [
  // --- SALÃO X PRIME (Lucas Silva) ---
  {
    id: 'off-1',
    salonName: 'Salão X Prime',
    professionalName: 'Lucas Silva',
    professionalAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Corte Degradê Navalhado',
    serviceCategory: 'cabelo',
    price: 45.0,
    originalPrice: 65.0,
    rating: 4.9,
    ratingCount: 142,
    distance: '650 metros',
    distanceMeters: 650,
    neighborhood: 'Itaquera, São Paulo',
    timeSlot: 'Hoje • 14:30',
    dayLabel: 'Hoje',
    duration: '45 min',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
    lat: -23.535,
    lng: -46.452,
    featured: true,
    mediaLevel: 3,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-barber-trimming-a-mans-beard-43093-large.mp4',
    expiresInMinutes: 12,
    expiresTimestamp: Date.now() + 12 * 60 * 1000,
    activeViewers: 6,
    isFlashDeal: true,
    isRecurring: true,
    recurringCount: 3,
    brandGradient: 'from-emerald-950 via-slate-900 to-zinc-950',
    description: 'Degradê na zero ou navalhado com finalização em pomada matte e toalha refrescante.',
  },
  {
    id: 'off-1b',
    salonName: 'Salão X Prime',
    professionalName: 'Lucas Silva',
    professionalAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Barboterapia com Toalha Quente',
    serviceCategory: 'barba',
    price: 35.0,
    originalPrice: 50.0,
    rating: 4.9,
    ratingCount: 118,
    distance: '650 metros',
    distanceMeters: 650,
    neighborhood: 'Itaquera, São Paulo',
    timeSlot: 'Hoje • 15:30',
    dayLabel: 'Hoje',
    duration: '35 min',
    imageUrl: 'https://images.unsplash.com/photo-1517832606299-7ae9b720a186?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1517832606299-7ae9b720a186?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
    ],
    lat: -23.535,
    lng: -46.452,
    mediaLevel: 2,
    expiresInMinutes: 20,
    expiresTimestamp: Date.now() + 20 * 60 * 1000,
    activeViewers: 4,
    isFlashDeal: true,
    brandGradient: 'from-emerald-950 via-slate-900 to-zinc-950',
    description: 'Barba alinhada com óleo vegetal, toalha aromatizada a vapor e pós-barba calmante.',
  },
  {
    id: 'off-1c',
    salonName: 'Salão X Prime',
    professionalName: 'Lucas Silva',
    professionalAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Combo Master: Corte + Barba + Sobrancelha',
    serviceCategory: 'cabelo',
    price: 70.0,
    originalPrice: 95.0,
    rating: 5.0,
    ratingCount: 89,
    distance: '650 metros',
    distanceMeters: 650,
    neighborhood: 'Itaquera, São Paulo',
    timeSlot: 'Hoje • 16:30',
    dayLabel: 'Hoje',
    duration: '75 min',
    imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517832606299-7ae9b720a186?auto=format&fit=crop&w=800&q=80',
    ],
    lat: -23.535,
    lng: -46.452,
    mediaLevel: 2,
    expiresInMinutes: 45,
    expiresTimestamp: Date.now() + 45 * 60 * 1000,
    activeViewers: 8,
    isFlashDeal: false,
    brandGradient: 'from-emerald-950 via-slate-900 to-zinc-950',
    description: 'Atendimento VIP completo com corte personalizado, barba na toalha quente e alinhamento de sobrancelhas.',
  },

  // --- BARBEARIA PRIMO (João Santos) ---
  {
    id: 'off-2',
    salonName: 'Barbearia Primo',
    professionalName: 'João Santos',
    professionalAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Corte Clássico & Barboterapia',
    serviceCategory: 'barba',
    price: 50.0,
    originalPrice: 75.0,
    rating: 4.9,
    ratingCount: 98,
    distance: '820 m',
    distanceMeters: 820,
    neighborhood: 'Itaquera, São Paulo',
    timeSlot: 'Hoje • 15:00',
    dayLabel: 'Hoje',
    duration: '60 min',
    imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80',
    ],
    lat: -23.538,
    lng: -46.456,
    mediaLevel: 2,
    expiresInMinutes: 24,
    expiresTimestamp: Date.now() + 24 * 60 * 1000,
    activeViewers: 3,
    isFlashDeal: true,
    brandGradient: 'from-amber-950 via-slate-900 to-zinc-950',
    description: 'Barba alinhada com toalha quente, óleos essenciais e massagem facial relaxante.',
  },
  {
    id: 'off-2b',
    salonName: 'Barbearia Primo',
    professionalName: 'João Santos',
    professionalAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Pigmentação de Barba & Alinhamento',
    serviceCategory: 'barba',
    price: 40.0,
    originalPrice: 60.0,
    rating: 4.8,
    ratingCount: 65,
    distance: '820 m',
    distanceMeters: 820,
    neighborhood: 'Itaquera, São Paulo',
    timeSlot: 'Hoje • 16:15',
    dayLabel: 'Hoje',
    duration: '40 min',
    imageUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=800&q=80',
    lat: -23.538,
    lng: -46.456,
    mediaLevel: 1,
    expiresInMinutes: 30,
    expiresTimestamp: Date.now() + 30 * 60 * 1000,
    activeViewers: 2,
    isFlashDeal: true,
    brandGradient: 'from-amber-950 via-slate-900 to-zinc-950',
    description: 'Preenchimento de falhas com pigmentação semipermanente de acabamento natural e contorno navalhado.',
  },

  // --- STUDIO MABE NAILS (Camila Rocha) ---
  {
    id: 'off-3',
    salonName: 'Studio Mabe Nails',
    professionalName: 'Camila Rocha',
    professionalAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Manicure & Esmaltação em Gel',
    serviceCategory: 'unhas',
    price: 40.0,
    originalPrice: 55.0,
    rating: 4.8,
    ratingCount: 84,
    distance: '1.1 km',
    distanceMeters: 1100,
    neighborhood: 'Artur Alvim, São Paulo',
    timeSlot: 'Hoje • 15:45',
    dayLabel: 'Hoje',
    duration: '50 min',
    imageUrl: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80',
    ],
    lat: -23.541,
    lng: -46.462,
    mediaLevel: 2,
    expiresInMinutes: 35,
    expiresTimestamp: Date.now() + 35 * 60 * 1000,
    activeViewers: 5,
    isFlashDeal: false,
    brandGradient: 'from-pink-950 via-slate-900 to-zinc-950',
    description: 'Cuticulagem perfeita, esmaltação em gel de alta durabilidade e hidratação com cera nutritiva.',
  },
  {
    id: 'off-3b',
    salonName: 'Studio Mabe Nails',
    professionalName: 'Camila Rocha',
    professionalAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Spa dos Pés com Esfoliação & Massagem',
    serviceCategory: 'unhas',
    price: 45.0,
    originalPrice: 65.0,
    rating: 4.9,
    ratingCount: 72,
    distance: '1.1 km',
    distanceMeters: 1100,
    neighborhood: 'Artur Alvim, São Paulo',
    timeSlot: 'Hoje • 17:00',
    dayLabel: 'Hoje',
    duration: '45 min',
    imageUrl: 'https://images.unsplash.com/photo-1519415943484-9fa1873496d4?auto=format&fit=crop&w=800&q=80',
    lat: -23.541,
    lng: -46.462,
    mediaLevel: 2,
    expiresInMinutes: 50,
    expiresTimestamp: Date.now() + 50 * 60 * 1000,
    activeViewers: 3,
    isFlashDeal: true,
    brandGradient: 'from-pink-950 via-slate-900 to-zinc-950',
    description: 'Imersão em sais aromáticos, remoção de asperezas, esfoliação com damasco e massagem podal.',
  },

  // --- DON STUDIO FACIAL (Juliana Mendes) ---
  {
    id: 'off-4',
    salonName: 'Don Studio Facial',
    professionalName: 'Juliana Mendes',
    professionalAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Design de Sobrancelha com Henna',
    serviceCategory: 'beleza',
    price: 35.0,
    originalPrice: 50.0,
    rating: 4.9,
    ratingCount: 210,
    distance: '450 m',
    distanceMeters: 450,
    neighborhood: 'Itaquera, São Paulo',
    timeSlot: 'Hoje • 16:30',
    dayLabel: 'Hoje',
    duration: '35 min',
    imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
    lat: -23.533,
    lng: -46.45,
    mediaLevel: 1, // Fallback ilustrado e animado
    expiresInMinutes: 18,
    expiresTimestamp: Date.now() + 18 * 60 * 1000,
    activeViewers: 8,
    isFlashDeal: true,
    brandGradient: 'from-purple-950 via-slate-900 to-zinc-950',
    description: 'Mapeamento facial com linha e aplicação de henna personalizada para o seu tom de pele.',
  },
  {
    id: 'off-4b',
    salonName: 'Don Studio Facial',
    professionalName: 'Juliana Mendes',
    professionalAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Lash Lifting & Nutrição de Cílios',
    serviceCategory: 'beleza',
    price: 65.0,
    originalPrice: 90.0,
    rating: 4.9,
    ratingCount: 114,
    distance: '450 m',
    distanceMeters: 450,
    neighborhood: 'Itaquera, São Paulo',
    timeSlot: 'Hoje • 17:30',
    dayLabel: 'Hoje',
    duration: '50 min',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80',
    lat: -23.533,
    lng: -46.45,
    mediaLevel: 2,
    expiresInMinutes: 40,
    expiresTimestamp: Date.now() + 40 * 60 * 1000,
    activeViewers: 5,
    isFlashDeal: true,
    brandGradient: 'from-purple-950 via-slate-900 to-zinc-950',
    description: 'Curvatura natural e elevação dos cílios naturais com tintura e botox capilar de queratina.',
  },

  // --- ESPAÇO GLAMOUR VIP (Renata Alencar) ---
  {
    id: 'off-5',
    salonName: 'Espaço Glamour VIP',
    professionalName: 'Renata Alencar',
    professionalAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Escova Modelada & Nutrição Capilar',
    serviceCategory: 'cabelo',
    price: 60.0,
    originalPrice: 85.0,
    rating: 4.9,
    ratingCount: 156,
    distance: '950 m',
    distanceMeters: 950,
    neighborhood: 'Vila Carmosina, São Paulo',
    timeSlot: 'Hoje • 16:00',
    dayLabel: 'Hoje',
    duration: '50 min',
    imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    ],
    lat: -23.539,
    lng: -46.459,
    mediaLevel: 2,
    expiresInMinutes: 28,
    expiresTimestamp: Date.now() + 28 * 60 * 1000,
    activeViewers: 7,
    isFlashDeal: true,
    brandGradient: 'from-rose-950 via-slate-900 to-zinc-950',
    description: 'Lavagem terapêutica com massagem capilar, máscara reconstrutora e escova com ondas duradouras.',
  },
  {
    id: 'off-5b',
    salonName: 'Espaço Glamour VIP',
    professionalName: 'Renata Alencar',
    professionalAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    serviceTitle: 'Limpeza de Pele Profunda + Peeling Ultrassônico',
    serviceCategory: 'estetica',
    price: 85.0,
    originalPrice: 120.0,
    rating: 5.0,
    ratingCount: 93,
    distance: '950 m',
    distanceMeters: 950,
    neighborhood: 'Vila Carmosina, São Paulo',
    timeSlot: 'Hoje • 18:00',
    dayLabel: 'Hoje',
    duration: '60 min',
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
    lat: -23.539,
    lng: -46.459,
    mediaLevel: 2,
    expiresInMinutes: 55,
    expiresTimestamp: Date.now() + 55 * 60 * 1000,
    activeViewers: 4,
    isFlashDeal: false,
    brandGradient: 'from-rose-950 via-slate-900 to-zinc-950',
    description: 'Extração indolor de cravos, esfoliação ultrassônica, máscara calmante e alta frequência.',
  },
];

export const INITIAL_BOOKINGS: BookingAppointment[] = [
  {
    protocolCode: '#VGA-12345',
    service: 'Corte masculino',
    professional: 'João',
    salonName: 'Salão X',
    dateTime: '02/09 às 14:30',
    dayGroup: 'HOJE, 26 DE JAN',
    time: '14:30',
    totalPrice: 45.0,
    status: 'EM ANDAMENTO',
    address: 'Rua Itaquera, 340 - São Paulo, SP',
  },
  {
    protocolCode: '#VGA-88310',
    service: 'Design de sobrancelha',
    professional: 'Rui',
    salonName: 'Studio Mabe',
    dateTime: '03/09 às 10:00',
    dayGroup: 'AMANHÃ, 27 DE JAN',
    time: '10:00',
    totalPrice: 35.0,
    status: 'AGENDADO',
    address: 'Av. Líder, 1200 - São Paulo, SP',
  },
  {
    protocolCode: '#VGA-99421',
    service: 'Barba + Toalha Quente',
    professional: 'Lucas',
    salonName: 'Barbearia Primo',
    dateTime: 'Amanhã • 15:30',
    dayGroup: 'AMANHÃ, 27 DE JAN',
    time: '15:30',
    totalPrice: 50.0,
    status: 'AGENDADO',
    address: 'Rua Campanella, 85 - São Paulo, SP',
  },
];
